# Generated by Django 4.1.7 on 2023-07-30 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_name',
            new_name='name',
        ),
    ]
